/**
 * Schedule Share - Image generation and sharing utilities
 * 
 * Generates shareable images of festival schedules
 */

import type { CrewSchedule } from "./schedule-planner";
import { formatTime } from "./schedule-planner";

/**
 * Schedule share data structure for image generation
 */
export interface ShareableSchedule {
  festivalName: string;
  crewName: string;
  day: string;
  slots: {
    time: string;
    artistName: string;
    stage: string;
    isHeadliner: boolean;
    isMeetup: boolean;
    crewCount: number;
    crewNames: string[];
  }[];
  conflicts: {
    time: string;
    options: { artistName: string; stage: string; crewNames: string[] }[];
  }[];
  stats: {
    setsCount: number;
    meetupsCount: number;
    conflictsCount: number;
  };
}

/**
 * Convert CrewSchedule to shareable format
 */
export function toShareableSchedule(
  schedule: CrewSchedule,
  festivalName: string,
  crewName: string
): ShareableSchedule {
  return {
    festivalName,
    crewName,
    day: schedule.day,
    slots: schedule.slots.map((slot) => ({
      time: `${formatTime(slot.timeSlot.startTime)} - ${formatTime(slot.timeSlot.endTime)}`,
      artistName: slot.artist.artistName,
      stage: slot.artist.stage,
      isHeadliner: slot.artist.headliner,
      isMeetup: slot.isMeetup && slot.meetupType === "all-crew",
      crewCount: slot.crewAttending.length,
      crewNames: slot.crewAttending.map((c) => c.displayName.split(" ")[0]),
    })),
    conflicts: schedule.conflicts.map((conflict) => ({
      time: `${formatTime(conflict.timeSlot.startTime)} - ${formatTime(conflict.timeSlot.endTime)}`,
      options: conflict.options.map((o) => ({
        artistName: o.artist.artistName,
        stage: o.artist.stage,
        crewNames: o.crewMembers.map((c) => c.displayName.split(" ")[0]),
      })),
    })),
    stats: {
      setsCount: schedule.slots.length,
      meetupsCount: schedule.meetups.filter((m) => m.type === "all-crew").length,
      conflictsCount: schedule.conflicts.length,
    },
  };
}

/**
 * Generate plain text schedule (for SMS/copy-paste)
 */
export function scheduleToText(
  schedules: CrewSchedule[],
  festivalName: string,
  crewName?: string
): string {
  const lines: string[] = [];
  const header = crewName 
    ? `📅 ${festivalName} - ${crewName}` 
    : `📅 ${festivalName}`;
  
  lines.push(header);
  lines.push("━".repeat(30));

  for (const schedule of schedules) {
    lines.push("");
    lines.push(`📍 ${schedule.day}`);
    lines.push("");

    // Sort all events by time
    const events: { time: number; text: string }[] = [];

    for (const slot of schedule.slots) {
      const meetupIcon = slot.isMeetup && slot.meetupType === "all-crew" ? " 🎯" : "";
      const headlinerIcon = slot.artist.headliner ? " ⭐" : "";
      const crewNames = slot.crewAttending.map((c) => c.displayName.split(" ")[0]).join(", ");
      
      events.push({
        time: slot.timeSlot.startMinutes,
        text: `${formatTime(slot.timeSlot.startTime)} ${slot.artist.artistName}${headlinerIcon}${meetupIcon}\n   📍 ${slot.artist.stage} | 👥 ${crewNames}`,
      });
    }

    for (const conflict of schedule.conflicts) {
      const options = conflict.options
        .map((o) => `${o.artist.artistName} (${o.crewMembers.map((c) => c.displayName.split(" ")[0]).join(", ")})`)
        .join(" vs ");
      
      events.push({
        time: conflict.timeSlot.startMinutes,
        text: `${formatTime(conflict.timeSlot.startTime)} ⚡ SPLIT: ${options}`,
      });
    }

    // Sort and add
    events.sort((a, b) => a.time - b.time);
    for (const event of events) {
      lines.push(event.text);
    }
  }

  lines.push("");
  lines.push("Generated by Stageside 🎵");
  
  return lines.join("\n");
}

/**
 * Generate compact schedule for social sharing
 */
export function scheduleToCompactText(
  schedules: CrewSchedule[],
  festivalName: string
): string {
  const lines: string[] = [`🎪 ${festivalName}\n`];

  for (const schedule of schedules) {
    const mustSee = schedule.slots
      .filter((s) => s.isMeetup && s.meetupType === "all-crew")
      .map((s) => s.artist.artistName);
    
    if (mustSee.length > 0) {
      lines.push(`${schedule.day}: ${mustSee.join(" → ")}`);
    }
  }

  lines.push("\n🎟️ stageside.app");
  return lines.join("\n");
}

/**
 * Web Share API wrapper
 */
export async function shareSchedule(
  title: string,
  text: string,
  url?: string
): Promise<boolean> {
  if (typeof navigator === "undefined" || !navigator.share) {
    // Fallback to clipboard
    try {
      await navigator.clipboard.writeText(text);
      return true;
    } catch {
      return false;
    }
  }

  try {
    await navigator.share({
      title,
      text,
      url,
    });
    return true;
  } catch (error) {
    // User cancelled or error
    console.error("Share failed:", error);
    return false;
  }
}

/**
 * Share with image (Web Share Level 2)
 */
export async function shareScheduleWithImage(
  title: string,
  text: string,
  imageBlob: Blob,
  filename: string = "schedule.png"
): Promise<boolean> {
  if (typeof navigator === "undefined" || !navigator.canShare) {
    return false;
  }

  const file = new File([imageBlob], filename, { type: "image/png" });
  const shareData = { title, text, files: [file] };

  if (!navigator.canShare(shareData)) {
    return false;
  }

  try {
    await navigator.share(shareData);
    return true;
  } catch {
    return false;
  }
}

/**
 * Download image blob
 */
export function downloadImage(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
