/**
 * Real Coachella 2026 Lineup
 * Dates: April 10-12 & 17-19, 2026
 */

export const coachella2026Lineup = [
  // HEADLINERS
  { artist_name: 'Sabrina Carpenter', headliner: true, genres: ['Pop'] },
  { artist_name: 'Justin Bieber', headliner: true, genres: ['Pop', 'R&B'] },
  { artist_name: 'Karol G', headliner: true, genres: ['Reggaeton', 'Latin Pop'] },
  { artist_name: 'Anyma', headliner: true, genres: ['Electronic', 'Techno'] },
  
  // Major Acts (alphabetical)
  { artist_name: 'Addison Rae', headliner: false, genres: ['Pop'] },
  { artist_name: 'Alex G', headliner: false, genres: ['Indie Rock'] },
  { artist_name: 'Armin van Buuren x Adam Beyer', headliner: false, genres: ['Trance', 'Techno'] },
  { artist_name: 'BIA', headliner: false, genres: ['Hip-Hop', 'Rap'] },
  { artist_name: 'BIGBANG', headliner: false, genres: ['K-Pop'] },
  { artist_name: 'BINI', headliner: false, genres: ['P-Pop'] },
  { artist_name: 'Black Flag', headliner: false, genres: ['Punk', 'Hardcore'] },
  { artist_name: 'Blood Orange', headliner: false, genres: ['R&B', 'Electronic'] },
  { artist_name: 'Blondshell', headliner: false, genres: ['Indie Rock'] },
  { artist_name: 'Boys Noize', headliner: false, genres: ['Electronic', 'Techno'] },
  { artist_name: 'Central Cee', headliner: false, genres: ['UK Rap', 'Hip-Hop'] },
  { artist_name: 'CLIPSE', headliner: false, genres: ['Hip-Hop', 'Rap'] },
  { artist_name: 'CMAT', headliner: false, genres: ['Country', 'Pop'] },
  { artist_name: 'Creepy Nuts', headliner: false, genres: ['J-Hip-Hop'] },
  { artist_name: 'David Byrne', headliner: false, genres: ['Art Rock', 'New Wave'] },
  { artist_name: 'David Guetta', headliner: false, genres: ['EDM', 'House'] },
  { artist_name: 'Davido', headliner: false, genres: ['Afrobeats'] },
  { artist_name: 'Devo', headliner: false, genres: ['New Wave', 'Synth-Pop'] },
  { artist_name: 'Dijon', headliner: false, genres: ['R&B', 'Indie'] },
  { artist_name: 'Disclosure', headliner: false, genres: ['Electronic', 'House'] },
  { artist_name: "DJ Snake's Pardon My French", headliner: false, genres: ['EDM', 'House'] },
  { artist_name: 'DRAIN', headliner: false, genres: ['Hardcore', 'Punk'] },
  { artist_name: 'Duke Dumont', headliner: false, genres: ['House', 'Electronic'] },
  { artist_name: 'Ethel Cain', headliner: false, genres: ['Indie', 'Gothic', 'Folk'] },
  { artist_name: 'Fatboy Slim', headliner: false, genres: ['Electronic', 'Big Beat'] },
  { artist_name: 'FKA twigs', headliner: false, genres: ['Art Pop', 'Electronic', 'R&B'] },
  { artist_name: 'Foster the People', headliner: false, genres: ['Indie Pop', 'Alternative'] },
  { artist_name: 'Fujii Kaze', headliner: false, genres: ['J-Pop', 'R&B'] },
  { artist_name: 'Geese', headliner: false, genres: ['Indie Rock'] },
  { artist_name: 'Gigi Perez', headliner: false, genres: ['Pop', 'Indie'] },
  { artist_name: 'GIVĒON', headliner: false, genres: ['R&B'] },
  { artist_name: 'Gordo', headliner: false, genres: ['House', 'Electronic'] },
  { artist_name: 'Green Velvet x AYYBO', headliner: false, genres: ['House', 'Techno'] },
  { artist_name: 'Groove Armada', headliner: false, genres: ['Electronic', 'House'] },
  { artist_name: 'Holly Humberstone', headliner: false, genres: ['Indie Pop'] },
  { artist_name: 'Hot Mulligan', headliner: false, genres: ['Emo', 'Pop Punk'] },
  { artist_name: 'Iggy Pop', headliner: false, genres: ['Punk', 'Rock'] },
  { artist_name: 'Interpol', headliner: false, genres: ['Post-Punk', 'Indie Rock'] },
  { artist_name: 'Jane Remover', headliner: false, genres: ['Hyperpop', 'Electronic'] },
  { artist_name: 'Levity', headliner: false, genres: ['Electronic'] },
  { artist_name: 'Moby', headliner: false, genres: ['Electronic', 'Ambient'] },
  { artist_name: 'Nine Inch Nails', headliner: false, genres: ['Industrial', 'Rock'] },
  { artist_name: 'Red Central', headliner: false, genres: ['Electronic'] },
  { artist_name: 'The Rapture', headliner: false, genres: ['Dance-Punk', 'Post-Punk'] },
  { artist_name: 'The Strokes', headliner: false, genres: ['Indie Rock', 'Garage Rock'] },
  { artist_name: 'The XX', headliner: false, genres: ['Indie Pop', 'Electronic'] },
  { artist_name: 'Turnstile', headliner: false, genres: ['Hardcore', 'Punk'] },
  { artist_name: 'Wednesday', headliner: false, genres: ['Indie Rock', 'Shoegaze'] },
];
